CREATE DISTRIBUTION ds1 COLUMN TYPES varchar hash;

CREATE KEY RANGE krid2 FROM 2147483648 ROUTE TO sh2 FOR DISTRIBUTION ds1;
CREATE KEY RANGE krid1 FROM 0 ROUTE TO sh1 FOR DISTRIBUTION ds1;

CREATE REFERENCE TABLE ENTITY_SCENARIOS;

ALTER DISTRIBUTION ds1 ATTACH RELATION ENTITIES DISTRIBUTION KEY ENTITY_ID HASH FUNCTION MURMUR;
ALTER DISTRIBUTION ds1 ATTACH RELATION REQUESTS DISTRIBUTION KEY ENTITY_ID HASH FUNCTION MURMUR;
ALTER DISTRIBUTION ds1 ATTACH RELATION SUBSCRIPTIONS DISTRIBUTION KEY ENTITY_ID HASH FUNCTION MURMUR;
ALTER DISTRIBUTION ds1 ATTACH RELATION RESPONSES DISTRIBUTION KEY ENTITY_ID HASH FUNCTION MURMUR;
ALTER DISTRIBUTION ds1 ATTACH RELATION ACTIVATION_EVENTS DISTRIBUTION KEY ENTITY_ID HASH FUNCTION MURMUR;
ALTER DISTRIBUTION ds1 ATTACH RELATION DELIVERIES DISTRIBUTION KEY ENTITY_ID HASH FUNCTION MURMUR;