CREATE TABLE DELIVERIES
(
    ENTITY_ID               VARCHAR(128) NOT NULL,
    ENTITY_CREATED_AT       TIMESTAMP(6) NOT NULL,
    SUBSCRIPTION_ID         VARCHAR(512)  NOT NULL,
    DELIVERED_AT            TIMESTAMP(6) NOT NULL
);