CREATE TABLE ACTIVATION_EVENTS
(
    ENTITY_ID               VARCHAR(128) NOT NULL,
    ENTITY_CREATED_AT       TIMESTAMP(6) NOT NULL,
    NAME                    VARCHAR(64)  NOT NULL,
    REGISTERED_AT           TIMESTAMP(6) NOT NULL
);
