CREATE TABLE REQUESTS
(
    REQUEST_ID              VARCHAR(512) NOT NULL,
    ENTITY_ID               VARCHAR(512) NOT NULL,
    ENTITY_CREATED_AT       TIMESTAMP(6) NOT NULL,
    CREATED_AT              TIMESTAMP(6) NOT NULL
);