CREATE TABLE SUBSCRIPTIONS
(
    ENTITY_ID               VARCHAR(512) NOT NULL,
    ENTITY_CREATED_AT       TIMESTAMP(6) NOT NULL,
    SUBSCRIBER_INFO         TEXT         NOT NULL,
    SUBSCRIPTION_ID         VARCHAR(512),
    CREATED_AT              TIMESTAMP(6) NOT NULL
);