# spring
server.port=8085

server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=false

# pool
server.tomcat.threads.min-spare=4
server.tomcat.threads.max=150
server.tomcat.connection-timeout=20000
server.tomcat.keep-alive-timeout=30000
server.tomcat.max-keep-alive-requests=10000
server.tomcat.max-http-form-post-size=2097152
server.tomcat.uri-encoding=UTF-8
server.max-http-header-size=65536

# datasource
database.jdbcUrl=jdbc:postgresql://localhost:6432/crabdb
database.username=crab
database.password=crab